name: Monthly WordCloud Generator

on:
  schedule:
    - cron: '0 20 1 * *'  # 8:00 PM UTC on the 1st
  workflow_dispatch:

jobs:
  generate-wordcloud:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run WordCloud Generator
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          MONGO_DB: brand_monitoring
          MONGO_COLLECTION: processed_articles
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
          SMTP_SERVER: smtp.gmail.com
          SMTP_PORT: 587
        run: python WordClouds.py
